server:
  port: 8082   # optional since default

spring:
  application:
    name:
      statisticservice

  datasource:
    url: jdbc:mysql://localhost:3306/db_statistics
    #change to your systems credentials
    username: root
    password: if20b204

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: travel.articles
          content-type: application/json
          group: travel.articles.group2
        consumer:
          concurrency: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true