GET http://localhost:8080/resources/articles

###

GET http://localhost:8080/resources/articles/1

###

DELETE http://localhost:8080/resources/articles/1

###

POST http://localhost:8080/resources/articles
Content-Type: application/json

{
  "title": "Hello Wiener!",
  "text": "Es ist wunderschoen",
  "publicationDate": "2021-01-01",
  "category": {
    "name": "Hofburg"
  },
  "authors": [
    {
      "id": 1,
      "sex": "MALE",
      "firstName": "Arber",
      "lastName": "Muca"
    },
    {
      "sex": "FEMALE",
      "firstName": "Norbert",
      "lastName": "Niemand"
    }
  ]
}

###

PUT http://localhost:8080/resources/articles/3
Content-Type: application/json

{
  "id": 3,
  "title": "Hello Wiener!",
  "text": "Es gibt doch wunderschoen hier.",
  "publicationDate": "2021-01-01",
  "category": {
    "id": 5,
    "name": "Hofburg"
  },
  "authors": [
    {
      "id": 1,
      "sex": "MALE",
      "firstName": "Arber",
      "lastName": "Muca"
    },
    {
      "id": 2,
      "sex": "FEMALE",
      "firstName": "Norbert",
      "lastName": "Niemand"
    }
  ]
}

###

DELETE http://localhost:8080/resources/articles/1

###